### ISSUE TITLE
UNRESPONSIVE extension host, 'njzy.stats-bar' took 100% of 5636.128ms

### ISSUE THREAD

**Issue by bersbersbers** [njzydark/vscode-stats-bar#1]
As soon as I enable the extension on Windows 10, VS Code 1.60, even with `"statsBar.modules": []`.

![image](https://user-images.githubusercontent.com/12128514/131897615-48f94dcd-d165-4154-8bf8-65c069d77af7.png)

**Comment by njzydark** [comment]
I'm working fine here and can't reproduce it, do you have this problem every time you start

**Comment by bersbersbers** [comment]
Yes, I do. After a restart, I may see something like this:
![image](https://user-images.githubusercontent.com/12128514/131950176-aea082a1-8b52-43e2-bcca-72c9e25ddcb2.png)

I do not have that problem on Linux (using Remote SSH from the same Windows 10 host, also using VS Code 1.60).

Not sure if that is related, but network up/down is showing 0 throughout on Windows (not on Linux).

**Comment by njzydark** [comment]
Can you try version 0.5.1, this time the problem I really can not reproduce here, and this issue does exist for a long time, I first temporarily closed

**Comment by bersbersbers** [comment]
Just tried v0.5.1 on 1.69.1 - same thing. Installing the extension makes my laptop fan go wild pretty much immediately. Task Manager shows several `PowerShell.exe` processes appear and disappear per second, that may be related.

**Comment by Nosferatu31** [comment]
> Just tried v0.5.1 on 1.69.1 - same thing. Installing the extension makes my laptop fan go wild pretty much immediately. Task Manager shows several `PowerShell.exe` processes appear and disappear per second, that may be related.

I have the same issue.

**Comment by njzydark** [comment]
> > Just tried v0.5.1 on 1.69.1 - same thing. Installing the extension makes my laptop fan go wild pretty much immediately. Task Manager shows several `PowerShell.exe` processes appear and disappear per second, that may be related.
> 
> I have the same issue.

try this command in your powershell, can you see some output?

```bash
Get-WmiObject Win32_PerfRawData_Tcpip_NetworkInterface | select Name,BytesReceivedPersec,PacketsReceivedErrors,PacketsReceivedDiscarded,BytesSentPersec,PacketsOutboundErrors,PacketsOutboundDiscarded | fl
```

**Comment by Nosferatu31** [comment]
> > > Just tried v0.5.1 on 1.69.1 - same thing. Installing the extension makes my laptop fan go wild pretty much immediately. Task Manager shows several `PowerShell.exe` processes appear and disappear per second, that may be related.
> > 
> > 
> > I have the same issue.
> 
> try this command in your powershell, can you see some output?
> 
> ```shell
> Get-WmiObject Win32_PerfRawData_Tcpip_NetworkInterface | select Name,BytesReceivedPersec,PacketsReceivedErrors,PacketsReceivedDiscarded,BytesSentPersec,PacketsOutboundErrors,PacketsOutboundDiscarded | fl
> ```

Yes I can

**Comment by njzydark** [comment]
@Nosferatu31  Have a try to new version - v0.5.2

**Comment by bersbersbers** [comment]
v0.5.2 on VS Code 1.70 does look much better indeed. Certainly what I describe in https://github.com/njzydark/vscode-stats-bar/issues/1#issuecomment-1186806913 is not happening any more. Thanks!

**Comment by Nosferatu31** [comment]
@njzydark all good now!
