### ISSUE TITLE
Incorrect value reported for used memory on MacOS

### ISSUE THREAD

**Issue by mikeburgh** [njzydark/vscode-stats-bar#2]
It appears to be reporting the wrong memory used value on MacOS.

The Activity monitor app on MacOS reports Memory used at 11.75GB (with 7.12 GB App Memory, 1.88 GB Wired Memory and 1.96 GB Compressed).
 
However the stats bar is reporting 1.39GB out of the total 16GB (which is right).

I checked it on Linux and Windows and the values were right, just the Mac that seems off.

**Comment by njzydark** [comment]
> It appears to be reporting the wrong memory used value on MacOS.
> 
> 
> 
> The Activity monitor app on MacOS reports Memory used at 11.75GB (with 7.12 GB App Memory, 1.88 GB Wired Memory and 1.96 GB Compressed).
> 
>  
> 
> However the stats bar is reporting 1.39GB out of the total 16GB (which is right).
> 
> 
> 
> I checked it on Linux and Windows and the values were right, just the Mac that seems off.

Apple M1?

**Comment by mikeburgh** [comment]
Yes, sorry should have mentioned that

**Comment by njzydark** [comment]
Update to v0.5.0 to fix this issue

PS: The displayed usage is still a bit off from the activity monitor, but I think it's irrelevant. Also, I added memory pressure (use `${pressurePercent}` to custom memory display format), which I think will be a more useful metric than memory usage

**Comment by mikeburgh** [comment]
Working great now!
