### ISSUE TITLE
publish package to "https://open-vsx.org"

### ISSUE THREAD

**Issue by TobiRoby** [njzydark/vscode-stats-bar#3]
Hey there,

I am currently looking for a cool vs code extension working with [code-server](https://github.com/coder/code-server/).
Since microsoft does not allow the usage of their extension marketplace would it be possible to publish your extension to the open source extension marketplace [open-vsx](https://open-vsx.org) as well?

Would love to monitor the resource usage on my developing machine while developing :)

**Comment by njzydark** [comment]
https://open-vsx.org/extension/njzy/stats-bar

**Comment by TobiRoby** [comment]
thx, works like a charm :)
