### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tlcd96** [njzydark/vscode-stats-bar#4]
- Issue Type: `Performance`
- Extension Name: `stats-bar`
- Extension Version: `0.5.1`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.70.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:heavy_check_mark:`file:///c%3A/Users/*******/AppData/Local/Temp/njzy.stats-bar-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[njzy.stats-bar-unresponsive.cpuprofile.txt](https://github.com/njzydark/vscode-stats-bar/files/9268738/njzy.stats-bar-unresponsive.cpuprofile.txt)

**Comment by njzydark** [comment]
Thank you for uploading the cpufile, I re-read the systeminformation performance related issues and found that this issue should be related to this https://github.com/sebhildebrandt/systeminformation/issues/616#issuecomment-974831564, Based on this I have released a new version - v0.5.2, you can try it out

**Comment by tlcd96** [comment]
the fix apparently fixed the problem, I'll close the issue since it's fixed, thanks :)
